/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ScoredDataArticle } from "./ScoredDataArticle";
import {
  ScoredDataArticleFromJSON,
  ScoredDataArticleFromJSONTyped,
  ScoredDataArticleToJSON,
  ScoredDataArticleToJSONTyped,
} from "./ScoredDataArticle";

/**
 * Articles vector search result
 * @export
 * @interface ArticlesVectorSearchResult
 */
export interface ArticlesVectorSearchResult {
  /**
   *
   * @type {number}
   * @memberof ArticlesVectorSearchResult
   */
  status: number;
  /**
   *
   * @type {Array<ScoredDataArticle>}
   * @memberof ArticlesVectorSearchResult
   */
  results: Array<ScoredDataArticle>;
}

/**
 * Check if a given object implements the ArticlesVectorSearchResult interface.
 */
export function instanceOfArticlesVectorSearchResult(
  value: object,
): value is ArticlesVectorSearchResult {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function ArticlesVectorSearchResultFromJSON(
  json: any,
): ArticlesVectorSearchResult {
  return ArticlesVectorSearchResultFromJSONTyped(json, false);
}

export function ArticlesVectorSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesVectorSearchResult {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    results: (json["results"] as Array<any>).map(ScoredDataArticleFromJSON),
  };
}

export function ArticlesVectorSearchResultToJSON(
  json: any,
): ArticlesVectorSearchResult {
  return ArticlesVectorSearchResultToJSONTyped(json, false);
}

export function ArticlesVectorSearchResultToJSONTyped(
  value?: ArticlesVectorSearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    results: (value["results"] as Array<any>).map(ScoredDataArticleToJSON),
  };
}
