/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CategoryHolder
 */
export interface CategoryHolder {
  /**
   *
   * @type {string}
   * @memberof CategoryHolder
   */
  name?: string | null;
}

/**
 * Check if a given object implements the CategoryHolder interface.
 */
export function instanceOfCategoryHolder(
  value: object,
): value is CategoryHolder {
  return true;
}

export function CategoryHolderFromJSON(json: any): CategoryHolder {
  return CategoryHolderFromJSONTyped(json, false);
}

export function CategoryHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CategoryHolder {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function CategoryHolderToJSON(json: any): CategoryHolder {
  return CategoryHolderToJSONTyped(json, false);
}

export function CategoryHolderToJSONTyped(
  value?: CategoryHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
  };
}
