/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CategoryWithScoreHolder
 */
export interface CategoryWithScoreHolder {
  /**
   *
   * @type {string}
   * @memberof CategoryWithScoreHolder
   */
  name?: string | null;
  /**
   *
   * @type {number}
   * @memberof CategoryWithScoreHolder
   */
  score?: number | null;
}

/**
 * Check if a given object implements the CategoryWithScoreHolder interface.
 */
export function instanceOfCategoryWithScoreHolder(
  value: object,
): value is CategoryWithScoreHolder {
  return true;
}

export function CategoryWithScoreHolderFromJSON(
  json: any,
): CategoryWithScoreHolder {
  return CategoryWithScoreHolderFromJSONTyped(json, false);
}

export function CategoryWithScoreHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CategoryWithScoreHolder {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    score: json["score"] == null ? undefined : json["score"],
  };
}

export function CategoryWithScoreHolderToJSON(
  json: any,
): CategoryWithScoreHolder {
  return CategoryWithScoreHolderToJSONTyped(json, false);
}

export function CategoryWithScoreHolderToJSONTyped(
  value?: CategoryWithScoreHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    score: value["score"],
  };
}
