/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityHolder
 */
export interface EntityHolder {
  /**
   *
   * @type {string}
   * @memberof EntityHolder
   */
  data?: string | null;
  /**
   *
   * @type {string}
   * @memberof EntityHolder
   */
  type?: string | null;
  /**
   *
   * @type {number}
   * @memberof EntityHolder
   */
  mentions?: number | null;
}

/**
 * Check if a given object implements the EntityHolder interface.
 */
export function instanceOfEntityHolder(value: object): value is EntityHolder {
  return true;
}

export function EntityHolderFromJSON(json: any): EntityHolder {
  return EntityHolderFromJSONTyped(json, false);
}

export function EntityHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntityHolder {
  if (json == null) {
    return json;
  }
  return {
    data: json["data"] == null ? undefined : json["data"],
    type: json["type"] == null ? undefined : json["type"],
    mentions: json["mentions"] == null ? undefined : json["mentions"],
  };
}

export function EntityHolderToJSON(json: any): EntityHolder {
  return EntityHolderToJSONTyped(json, false);
}

export function EntityHolderToJSONTyped(
  value?: EntityHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value["data"],
    type: value["type"],
    mentions: value["mentions"],
  };
}
