/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventTypeHolder
 */
export interface EventTypeHolder {
  /**
   *
   * @type {string}
   * @memberof EventTypeHolder
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof EventTypeHolder
   */
  type?: string | null;
}

/**
 * Check if a given object implements the EventTypeHolder interface.
 */
export function instanceOfEventTypeHolder(
  value: object,
): value is EventTypeHolder {
  return true;
}

export function EventTypeHolderFromJSON(json: any): EventTypeHolder {
  return EventTypeHolderFromJSONTyped(json, false);
}

export function EventTypeHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EventTypeHolder {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    type: json["type"] == null ? undefined : json["type"],
  };
}

export function EventTypeHolderToJSON(json: any): EventTypeHolder {
  return EventTypeHolderToJSONTyped(json, false);
}

export function EventTypeHolderToJSONTyped(
  value?: EventTypeHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    type: value["type"],
  };
}
