/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { z } from "zod";

export const AllEndpointSortBySchema = z.enum([
  "relevance",
  "date",
  "reverseDate",
  "reverseAddDate",
  "addDate",
  "pubDate",
  "refreshDate",
]);

export type AllEndpointSortBy = z.infer<typeof AllEndpointSortBySchema>;

export const AllEndpointSortBy = {
  Relevance: "relevance",
  Date: "date",
  ReverseDate: "reverseDate",
  ReverseAddDate: "reverseAddDate",
  AddDate: "addDate",
  PubDate: "pubDate",
  RefreshDate: "refreshDate",
} as const;

export const CategoryHolderSchema = z.object({
  /**
   * Content category assigned to the article.
   */
  name: z.string().optional().nullable(),
});

export type CategoryHolder = z.infer<typeof CategoryHolderSchema>;

export const CategoryWithScoreHolderSchema = z.object({
  /**
   * Full taxonomy category path.
   */
  name: z.string().optional().nullable(),
  /**
   * Confidence score for the category assignment.
   */
  score: z.number().optional().nullable(),
});

export type CategoryWithScoreHolder = z.infer<
  typeof CategoryWithScoreHolderSchema
>;

export const CompanyHolderSchema = z.object({
  /**
   * Unique Perigon identifier for the company.
   */
  id: z.string().optional().nullable(),
  /**
   * Company name.
   */
  name: z.string().optional().nullable(),
  /**
   * Domains associated with the company.
   */
  domains: z.array(z.string()).optional().nullable(),
  /**
   * Stock symbols associated with the company.
   */
  symbols: z.array(z.string()).optional().nullable(),
});

export type CompanyHolder = z.infer<typeof CompanyHolderSchema>;

export const EntityHolderSchema = z.object({
  /**
   * Text value of the extracted entity.
   */
  data: z.string().optional().nullable(),
  /**
   * Entity type, such as PERSON, ORGANIZATION, or LOCATION.
   */
  type: z.string().optional().nullable(),
  /**
   * Number of times the entity appears in the article.
   */
  mentions: z.number().optional().nullable(),
});

export type EntityHolder = z.infer<typeof EntityHolderSchema>;

export const EventTypeHolderSchema = z.object({
  /**
   * Detected event name.
   */
  name: z.string().optional().nullable(),
  /**
   * Detected event classification.
   */
  type: z.string().optional().nullable(),
});

export type EventTypeHolder = z.infer<typeof EventTypeHolderSchema>;

export const IdNameHolderSchema = z.object({
  /**
   * Unique identifier for the matched record.
   */
  id: z.string().optional().nullable(),
  /**
   * Display name of the matched record.
   */
  name: z.string().optional().nullable(),
});

export type IdNameHolder = z.infer<typeof IdNameHolderSchema>;

export const LocationHolderSchema = z.object({
  /**
   * Country central to the article.
   */
  country: z.string().optional().nullable(),
  /**
   * State or region central to the article.
   */
  state: z.string().optional().nullable(),
  /**
   * County central to the article.
   */
  county: z.string().optional().nullable(),
  /**
   * City central to the article.
   */
  city: z.string().optional().nullable(),
  /**
   * Neighborhood, borough, or district central to the article.
   */
  area: z.string().optional().nullable(),
});

export type LocationHolder = z.infer<typeof LocationHolderSchema>;

export const NameCountSchema = z.object({
  /**
   * Name of the aggregated value.
   */
  name: z.string().optional().nullable(),
  /**
   * Number of matching records for the value.
   */
  count: z.number().optional().nullable(),
});

export type NameCount = z.infer<typeof NameCountSchema>;

export const JournalistSchema = z.object({
  /**
   * Unique Perigon identifier for the journalist.
   */
  id: z.string().optional().nullable(),
  primaryRecordId: z.string().optional().nullable(),
  /**
   * Common display name of the journalist.
   */
  name: z.string().optional().nullable(),
  /**
   * Full name of the journalist.
   */
  fullName: z.string().optional().nullable(),
  /**
   * Professional headline associated with the journalist.
   */
  headline: z.string().optional().nullable(),
  /**
   * Biographical description of the journalist.
   */
  description: z.string().optional().nullable(),
  /**
   * Professional title of the journalist.
   */
  title: z.string().optional().nullable(),
  /**
   * Journalist's email.
   */
  email: z.string().optional().nullable(),
  /**
   * Locations associated with the journalist.
   */
  locations: z.array(LocationHolderSchema).optional().nullable(),
  /**
   * Date and time the journalist record was last refreshed, in ISO 8601 format.
   */
  updatedAt: z.string().optional().nullable(),
  /**
   * Topics most frequently covered by the journalist.
   */
  topTopics: z.array(NameCountSchema).optional().nullable(),
  /**
   * Publishers most frequently associated with the journalist.
   */
  topSources: z.array(NameCountSchema).optional().nullable(),
  /**
   * Categories most frequently covered by the journalist.
   */
  topCategories: z.array(NameCountSchema).optional().nullable(),
  /**
   * Editorial labels most frequently associated with the journalist's articles.
   */
  topLabels: z.array(NameCountSchema).optional().nullable(),
  /**
   * Countries most frequently associated with the journalist's articles.
   */
  topCountries: z.array(NameCountSchema).optional().nullable(),
  /**
   * Average number of articles published by the journalist per month.
   */
  avgMonthlyPosts: z.number().optional().nullable(),
  /**
   * Journalist's X or Twitter handle.
   */
  twitterHandle: z.string().optional().nullable(),
  /**
   * Biography from the journalist's X or Twitter profile.
   */
  twitterBio: z.string().optional().nullable(),
  /**
   * Profile image URL for the journalist.
   */
  imageUrl: z.string().optional().nullable(),
  /**
   * LinkedIn profile URL for the journalist.
   */
  linkedinUrl: z.string().optional().nullable(),
  /**
   * LinkedIn connection count for the journalist, when available.
   */
  linkedinConnections: z.number().optional().nullable(),
  /**
   * LinkedIn follower count for the journalist, when available.
   */
  linkedinFollowers: z.number().optional().nullable(),
  /**
   * Facebook profile URL for the journalist.
   */
  facebookUrl: z.string().optional().nullable(),
  /**
   * Instagram profile URL for the journalist.
   */
  instagramUrl: z.string().optional().nullable(),
  /**
   * Personal or professional website URL for the journalist.
   */
  websiteUrl: z.string().optional().nullable(),
  /**
   * Blog URL for the journalist.
   */
  blogUrl: z.string().optional().nullable(),
  /**
   * Tumblr profile URL for the journalist.
   */
  tumblrUrl: z.string().optional().nullable(),
  /**
   * YouTube channel URL for the journalist.
   */
  youtubeUrl: z.string().optional().nullable(),
});

export type Journalist = z.infer<typeof JournalistSchema>;

export const KeywordHolderSchema = z.object({
  /**
   * Keyword extracted from the article.
   */
  name: z.string().optional().nullable(),
  /**
   * Relative relevance weight of the keyword.
   */
  weight: z.number().optional().nullable(),
});

export type KeywordHolder = z.infer<typeof KeywordHolderSchema>;

export const LabelHolderSchema = z.object({
  /**
   * Editorial label assigned to the article.
   */
  name: z.string().optional().nullable(),
});

export type LabelHolder = z.infer<typeof LabelHolderSchema>;

export const CompanyCountSchema = z.object({
  /**
   * Unique Perigon identifier for the company.
   */
  id: z.string().optional().nullable(),
  /**
   * Company name.
   */
  name: z.string().optional().nullable(),
  /**
   * Domains associated with the company.
   */
  domains: z.array(z.string()).optional().nullable(),
  /**
   * Stock symbols associated with the company.
   */
  symbols: z.array(z.string()).optional().nullable(),
  /**
   * Number of story articles mentioning the company.
   */
  count: z.number().optional().nullable(),
});

export type CompanyCount = z.infer<typeof CompanyCountSchema>;

export const KeyPointSchema = z.object({
  /**
   * A key fact or development identified in the content.
   */
  point: z.string().optional().nullable(),
  /**
   * Article IDs supporting the key point.
   */
  references: z.array(z.string()).optional().nullable(),
});

export type KeyPoint = z.infer<typeof KeyPointSchema>;

export const LocationCountSchema = z.object({
  /**
   * Country associated with the story.
   */
  country: z.string().optional().nullable(),
  /**
   * State or region associated with the story.
   */
  state: z.string().optional().nullable(),
  /**
   * County associated with the story.
   */
  county: z.string().optional().nullable(),
  /**
   * City associated with the story.
   */
  city: z.string().optional().nullable(),
  /**
   * Neighborhood, borough, or district associated with the story.
   */
  area: z.string().optional().nullable(),
  /**
   * Number of story articles associated with the location.
   */
  count: z.number().optional().nullable(),
});

export type LocationCount = z.infer<typeof LocationCountSchema>;

export const PersonCountSchema = z.object({
  /**
   * Wikidata identifier for the person.
   */
  wikidataId: z.string().optional().nullable(),
  /**
   * Person name.
   */
  name: z.string().optional().nullable(),
  /**
   * Number of story articles mentioning the person.
   */
  count: z.number().optional().nullable(),
});

export type PersonCount = z.infer<typeof PersonCountSchema>;

export const PersonHolderSchema = z.object({
  /**
   * Wikidata identifier for the person.
   */
  wikidataId: z.string().optional().nullable(),
  /**
   * Person name.
   */
  name: z.string().optional().nullable(),
});

export type PersonHolder = z.infer<typeof PersonHolderSchema>;

export const QuestionSchema = z.object({
  /**
   * Question generated from the story content.
   */
  question: z.string().optional().nullable(),
  /**
   * Answer generated from the story content.
   */
  answer: z.string().optional().nullable(),
  /**
   * Article IDs supporting the answer.
   */
  references: z.array(z.string()).optional().nullable(),
});

export type Question = z.infer<typeof QuestionSchema>;

export const RecordStatHolderSchema = z.object({
  /**
   * Name of the aggregated value.
   */
  name: z.string().optional().nullable(),
  /**
   * Number of matching articles for the value.
   */
  count: z.number().optional().nullable(),
});

export type RecordStatHolder = z.infer<typeof RecordStatHolderSchema>;

export const SentimentHolderSchema = z.object({
  /**
   * Positive sentiment score from 0 to 1.
   */
  positive: z.number().optional().nullable(),
  /**
   * Negative sentiment score from 0 to 1.
   */
  negative: z.number().optional().nullable(),
  /**
   * Neutral sentiment score from 0 to 1.
   */
  neutral: z.number().optional().nullable(),
});

export type SentimentHolder = z.infer<typeof SentimentHolderSchema>;

export const CoordinateSchema = z.object({
  /**
   * Latitude in decimal degrees.
   */
  lat: z.number().optional().nullable(),
  /**
   * Longitude in decimal degrees.
   */
  lon: z.number().optional().nullable(),
});

export type Coordinate = z.infer<typeof CoordinateSchema>;

export const SourceLocationSchema = z.object({
  /**
   * Country where the publisher is located.
   */
  country: z.string().optional().nullable(),
  /**
   * State or region where the publisher is located.
   */
  state: z.string().optional().nullable(),
  /**
   * County where the publisher is located.
   */
  county: z.string().optional().nullable(),
  /**
   * City where the publisher is located.
   */
  city: z.string().optional().nullable(),
  coordinates: CoordinateSchema.optional().nullable(),
});

export type SourceLocation = z.infer<typeof SourceLocationSchema>;

export const SourceHolderSchema = z.object({
  /**
   * Publisher domain.
   */
  domain: z.string().optional().nullable(),
  /**
   * Whether the publisher uses a paywall, when known.
   */
  paywall: z.boolean().optional().nullable(),
  location: SourceLocationSchema.optional().nullable(),
});

export type SourceHolder = z.infer<typeof SourceHolderSchema>;

export const TopicHolderSchema = z.object({
  /**
   * Topic assigned to the article.
   */
  name: z.string().optional().nullable(),
});

export type TopicHolder = z.infer<typeof TopicHolderSchema>;

export const NewsClusterSchema = z.object({
  /**
   * Date and time the story was created, in ISO 8601 format.
   */
  createdAt: z.string().optional().nullable(),
  /**
   * Date and time the story was last updated, in ISO 8601 format.
   */
  updatedAt: z.string().optional().nullable(),
  /**
   * Date and time the story became initialized and visible, in ISO 8601 format.
   */
  initializedAt: z.string().optional().nullable(),
  /**
   * Unique identifier for the story cluster.
   */
  id: z.string().optional().nullable(),
  /**
   * Identifier of the original story when this story is a duplicate.
   */
  duplicateOf: z.string().optional().nullable(),
  /**
   * URL-safe identifier for the story.
   */
  slug: z.string().optional().nullable(),
  /**
   * Generated story title.
   */
  name: z.string().optional().nullable(),
  /**
   * Generated story summary.
   */
  summary: z.string().optional().nullable(),
  /**
   * Short generated story summary, when available.
   */
  shortSummary: z.string().optional().nullable(),
  /**
   * Article IDs supporting the story summary.
   */
  summaryReferences: z.array(z.string()).optional().nullable(),
  imageSource: SourceHolderSchema.optional().nullable(),
  /**
   * Primary image URL selected for the story.
   */
  imageUrl: z.string().optional().nullable(),
  /**
   * Key facts and developments identified in the story.
   */
  keyPoints: z.array(KeyPointSchema).optional().nullable(),
  /**
   * Questions and answers generated from the story content.
   */
  questions: z.array(QuestionSchema).optional().nullable(),
  /**
   * Distinct publisher domains represented in the story.
   */
  uniqueSources: z.array(z.string()).optional().nullable(),
  /**
   * Representative articles selected for the story.
   */
  selectedArticles: z
    .array(z.unknown() /* Circular reference to ArticleSchema */)
    .optional()
    .nullable(),
  sentiment: SentimentHolderSchema.optional().nullable(),
  /**
   * Number of unique articles in the story.
   */
  uniqueCount: z.number().optional().nullable(),
  /**
   * Number of reprinted articles in the story.
   */
  reprintCount: z.number().optional().nullable(),
  /**
   * Total article count including reprints.
   */
  totalCount: z.number().optional().nullable(),
  /**
   * Countries associated with the story and their article counts.
   */
  countries: z.array(RecordStatHolderSchema).optional().nullable(),
  /**
   * Countries most strongly associated with the story.
   */
  topCountries: z.array(z.string()).optional().nullable(),
  /**
   * Topics associated with the story and their article counts.
   */
  topics: z.array(RecordStatHolderSchema).optional().nullable(),
  /**
   * Topics most strongly associated with the story.
   */
  topTopics: z.array(TopicHolderSchema).optional().nullable(),
  /**
   * Categories associated with the story and their article counts.
   */
  categories: z.array(RecordStatHolderSchema).optional().nullable(),
  /**
   * Categories most strongly associated with the story.
   */
  topCategories: z.array(CategoryHolderSchema).optional().nullable(),
  /**
   * Google Content Categories associated with the story and their article counts.
   */
  taxonomies: z.array(RecordStatHolderSchema).optional().nullable(),
  /**
   * Google Content Categories most strongly associated with the story.
   */
  topTaxonomies: z.array(CategoryHolderSchema).optional().nullable(),
  /**
   * People associated with the story and their article counts.
   */
  people: z.array(PersonCountSchema).optional().nullable(),
  /**
   * People most strongly associated with the story.
   */
  topPeople: z.array(PersonHolderSchema).optional().nullable(),
  /**
   * Companies associated with the story and their article counts.
   */
  companies: z.array(CompanyCountSchema).optional().nullable(),
  /**
   * Companies most strongly associated with the story.
   */
  topCompanies: z.array(CompanyHolderSchema).optional().nullable(),
  /**
   * Locations associated with the story and their article counts.
   */
  locations: z.array(LocationCountSchema).optional().nullable(),
  /**
   * Locations most strongly associated with the story.
   */
  topLocations: z.array(LocationHolderSchema).optional().nullable(),
  /**
   * Matched text fragments grouped by story field.
   */
  highlights: z.record(z.string(), z.array(z.string())).optional().nullable(),
  /**
   * Ratio of unique publisher domains to total articles in the story.
   */
  sourceDiversity: z.number().optional().nullable(),
});

export type NewsCluster = z.infer<typeof NewsClusterSchema>;

export const PlaceSchema = z.object({
  /**
   * OpenStreetMap identifier for the place.
   */
  osmId: z.string().optional().nullable(),
  /**
   * Road associated with the place.
   */
  road: z.string().optional().nullable(),
  /**
   * Quarter associated with the place.
   */
  quarter: z.string().optional().nullable(),
  /**
   * Suburb associated with the place.
   */
  suburb: z.string().optional().nullable(),
  /**
   * City associated with the place.
   */
  city: z.string().optional().nullable(),
  /**
   * Town associated with the place.
   */
  town: z.string().optional().nullable(),
  /**
   * County associated with the place.
   */
  county: z.string().optional().nullable(),
  /**
   * State district associated with the place.
   */
  stateDistrict: z.string().optional().nullable(),
  /**
   * State or region associated with the place.
   */
  state: z.string().optional().nullable(),
  /**
   * Postal code associated with the place.
   */
  postcode: z.string().optional().nullable(),
  /**
   * Country associated with the place.
   */
  country: z.string().optional().nullable(),
  /**
   * Two-character country code for the place.
   */
  countryCode: z.string().optional().nullable(),
  /**
   * Named amenity associated with the place.
   */
  amenity: z.string().optional().nullable(),
  /**
   * Neighborhood associated with the place.
   */
  neighbourhood: z.string().optional().nullable(),
  coordinates: CoordinateSchema.optional().nullable(),
});

export type Place = z.infer<typeof PlaceSchema>;

export const ArticleSchema = z.object({
  /**
   * Canonical URL of the article.
   */
  url: z.string().optional().nullable(),
  /**
   * Author byline as published by the source.
   */
  authorsByline: z.string().optional().nullable(),
  /**
   * Unique Perigon identifier for the article.
   */
  articleId: z.string().optional().nullable(),
  /**
   * Identifier of the story cluster containing the article, when assigned.
   */
  clusterId: z.string().optional().nullable(),
  source: SourceHolderSchema.optional().nullable(),
  /**
   * Primary image URL associated with the article.
   */
  imageUrl: z.string().optional().nullable(),
  /**
   * Two-character country code associated with the article.
   */
  country: z.string().optional().nullable(),
  /**
   * ISO 639 two-letter language code for the article.
   */
  language: z.string().optional().nullable(),
  /**
   * Date and time the article was published, in ISO 8601 format.
   */
  pubDate: z.string().optional().nullable(),
  /**
   * Date and time the article was added to Perigon, in ISO 8601 format.
   */
  addDate: z.string().optional().nullable(),
  /**
   * Date and time the article was last refreshed by Perigon, in ISO 8601 format.
   */
  refreshDate: z.string().optional().nullable(),
  /**
   * Search relevance score for the article, when applicable.
   */
  score: z.number().optional().nullable(),
  /**
   * Article headline.
   */
  title: z.string().optional().nullable(),
  /**
   * Article description or publisher-provided excerpt.
   */
  description: z.string().optional().nullable(),
  /**
   * Full article body available to Perigon.
   */
  content: z.string().optional().nullable(),
  /**
   * Word count of the English article content, when available.
   */
  enContentWordCount: z.number().optional().nullable(),
  /**
   * Primary medium type, such as Article or Video.
   */
  medium: z.string().optional().nullable(),
  /**
   * URLs linked from the article content.
   */
  links: z.array(z.string()).optional().nullable(),
  /**
   * Editorial labels assigned to the article.
   */
  labels: z.array(LabelHolderSchema).optional().nullable(),
  /**
   * Event types detected in the article.
   */
  eventTypes: z.array(EventTypeHolderSchema).optional().nullable(),
  /**
   * Known journalist records matched to the article byline.
   */
  matchedAuthors: z.array(IdNameHolderSchema).optional().nullable(),
  /**
   * Claim identified in fact-check content, when applicable.
   */
  claim: z.string().optional().nullable(),
  /**
   * Verdict identified in fact-check content, when applicable.
   */
  verdict: z.string().optional().nullable(),
  /**
   * Keywords extracted from the article with their relevance weights.
   */
  keywords: z.array(KeywordHolderSchema).optional().nullable(),
  /**
   * Topics assigned to the article.
   */
  topics: z.array(TopicHolderSchema).optional().nullable(),
  /**
   * Broad content categories assigned to the article.
   */
  categories: z.array(CategoryHolderSchema).optional().nullable(),
  /**
   * Google Content Categories assigned to the article with confidence scores.
   */
  taxonomies: z.array(CategoryWithScoreHolderSchema).optional().nullable(),
  /**
   * Named entities extracted from the article.
   */
  entities: z.array(EntityHolderSchema).optional().nullable(),
  /**
   * Companies identified in the article.
   */
  companies: z.array(CompanyHolderSchema).optional().nullable(),
  sentiment: SentimentHolderSchema.optional().nullable(),
  /**
   * Generated summary of the article, when available.
   */
  summary: z.string().optional().nullable(),
  /**
   * Short generated summary of the article, when available.
   */
  shortSummary: z.string().optional().nullable(),
  /**
   * Translated article content, when available.
   */
  translation: z.string().optional().nullable(),
  /**
   * English translation of the article title, when available.
   */
  translatedTitle: z.string().optional().nullable(),
  /**
   * English translation of the article description, when available.
   */
  translatedDescription: z.string().optional().nullable(),
  /**
   * English translation of the article summary, when available.
   */
  translatedSummary: z.string().optional().nullable(),
  /**
   * Locations identified as central to the article.
   */
  locations: z.array(LocationHolderSchema).optional().nullable(),
  /**
   * Whether the article is a reprint of previously published content.
   */
  reprint: z.boolean().optional().nullable(),
  /**
   * Identifier grouping the original article with its known reprints.
   */
  reprintGroupId: z.string().optional().nullable(),
  /**
   * Structured geographic places extracted from the article.
   */
  places: z.array(PlaceSchema).optional().nullable(),
  /**
   * Known people identified in the article.
   */
  people: z.array(PersonHolderSchema).optional().nullable(),
  cluster: NewsClusterSchema.optional().nullable(),
  /**
   * Expanded journalist details, when requested and available.
   */
  journalists: z.array(JournalistSchema).optional().nullable(),
  /**
   * Matched text fragments grouped by article field.
   */
  highlights: z.record(z.string(), z.array(z.string())).optional().nullable(),
});

export type Article = z.infer<typeof ArticleSchema>;

export const CoordinateFilterSchema = z.object({
  lat: z.number().optional().nullable(),
  lon: z.number().optional().nullable(),
  radius: z.number().optional().nullable(),
});

export type CoordinateFilter = z.infer<typeof CoordinateFilterSchema>;

export const ArticleSearchFilterSchema = z.object({
  /**
   * Filter by specific article identifiers. Accepts either a single ID or an array of IDs. Returns only articles matching these IDs.
   */
  articleId: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific story identifiers. Accepts either a single ID or an array of IDs. Returns only articles belonging to these stories.
   */
  clusterId: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by specific publisher domains or subdomains. Accepts either a single domain or an array of domains. Multiple values create an OR filter.
   */
  source: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles from specific publisher domains or subdomains. Accepts either a single domain or an array of domains. Multiple values create an AND-exclude filter.
   */
  excludeSource: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles using Perigon's curated publisher bundles (e.g., top100, top25tech). Accepts either a single source group or an array. Multiple values create an OR filter to include articles from any of the specified bundles.
   */
  sourceGroup: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by their language using ISO-639 two-letter codes in lowercase (e.g., en, es, fr). Accepts either a single language code or an array. Multiple values create an OR filter.
   */
  language: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles in specific languages using ISO-639 two-letter codes in lowercase. Accepts either a single language code or an array. Multiple values create an AND-exclude filter.
   */
  excludeLanguage: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by editorial labels such as Opinion, Paid-news, Non-news, Fact Check, or Press Release. View our docs for an exhaustive list of labels. Accepts either a single label or an array. Multiple values create an OR filter.
   */
  label: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles with specific editorial labels. Accepts either a single label or an array. Multiple values create an AND-exclude filter, removing all content with any of these labels.
   */
  excludeLabel: z.array(z.string()).optional().nullable(),
  /**
   * Filter by Google Content Categories. Must pass the full hierarchical path of the category. Accepts either a single path or an array. Example: taxonomy=/Finance/Banking/Other,/Finance/Investing/Funds. Multiple values create an OR filter.
   */
  taxonomy: z.array(z.string()).optional().nullable(),
  /**
   * Filter by broad content categories such as Politics, Tech, Sports, Business, or Finance. Accepts either a single category or an array. Use none to find uncategorized articles. Multiple values create an OR filter.
   */
  category: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific topics such as Markets, Crime, Cryptocurrency, or College Sports. Accepts either a single topic or an array. Topics are more granular than categories, and articles can have multiple topics. Multiple values create an OR filter.
   */
  topic: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles with specific topics. Accepts either a single topic or an array. Multiple values create an AND-exclude filter, removing all content with any of these topics.
   */
  excludeTopic: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by countries they mention using two-letter country codes in lowercase (e.g., us, gb, jp). Accepts either a single country code or an array. Multiple values create an OR filter. See documentation for supported country codes.
   */
  country: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles from specific countries using two-letter country codes in lowercase. Accepts either a single country code or an array. Multiple values create an AND-exclude filter. See documentation for supported country codes.
   */
  excludeCountry: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles where specified countries play a central role in the content, not just mentioned. Uses two-letter country codes in lowercase. Accepts either a single country code or an array. Multiple values create an OR filter. See documentation for supported country codes.
   */
  locationsCountry: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles where specified countries play a central role in the content. Accepts either a single country code or an array. Multiple values create an AND-exclude filter, removing articles focused on any of these countries. See documentation for supported country codes.
   */
  excludeLocationsCountry: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles where specified states play a central role in the content. Accepts either a single state code or an array. Multiple values create an OR filter. Uses two-letter state codes in lowercase. See documentation for supported state codes.
   */
  state: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles where specified states play a central role. Accepts either a single state code or an array. Multiple values create an AND-exclude filter, removing articles focused on any of these states. See documentation for supported state codes.
   */
  excludeState: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles that mention or are related to specific counties. Accepts either a single county name or an array. Multiple values create an OR filter. County names typically include the word 'County' (e.g., Los Angeles County).
   */
  county: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles that mention or are related to specific counties. Accepts either a single county name or an array. Multiple values create an AND-exclude filter. County names should match the format in article metadata (e.g., Los Angeles County, Cook County).
   */
  excludeCounty: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles that mention or are related to specific cities. Accepts either a single city name or an array. Multiple values create an OR filter.
   */
  city: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles that mention or are related to specific cities. Accepts either a single city name or an array. Multiple values create an AND-exclude filter.
   */
  excludeCity: z.array(z.string()).optional().nullable(),
  /**
   * Filter for articles from publishers based in specific countries. Accepts either a single country code or an array. Uses two-letter country codes in lowercase (e.g., us, gb). See documentation for supported country codes.
   */
  sourceCountry: z.array(z.string()).optional().nullable(),
  /**
   * Filter for articles from publishers based in specific states or regions. Accepts either a single state code or an array. Uses two-letter state codes in lowercase. See documentation for supported state codes.
   */
  sourceState: z.array(z.string()).optional().nullable(),
  /**
   * Filter for articles from publishers based in specific counties. Accepts either a single county name or an array. Multiple values create an OR filter.
   */
  sourceCounty: z.array(z.string()).optional().nullable(),
  /**
   * Filter for articles from publishers based in specific cities. Accepts either a single city name or an array. Multiple values create an OR filter.
   */
  sourceCity: z.array(z.string()).optional().nullable(),
  coordinates: CoordinateFilterSchema.optional().nullable(),
  sourceCoordinates: CoordinateFilterSchema.optional().nullable(),
  /**
   * Filter articles by company identifiers. Accepts either a single ID or an array. Multiple values create an OR filter. For a complete list of tracked companies and their IDs, refer to the /companies endpoint.
   */
  companyId: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles mentioning companies with specific identifiers. Accepts either a single ID or an array. Multiple values create an AND-exclude filter. For a complete list of tracked companies and their IDs, refer to the /companies endpoint.
   */
  excludeCompanyId: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by company domains (e.g., apple.com). Accepts either a single domain or an array. Multiple values create an OR filter. For a complete list of tracked companies and their domains, refer to the /companies endpoint.
   */
  companyDomain: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles related to companies with specific domains. Accepts either a single domain or an array. Multiple values create an AND-exclude filter. For a complete list of tracked companies and their domains, refer to the /companies endpoint.
   */
  excludeCompanyDomain: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by company stock symbols (e.g., AAPL, MSFT). Accepts either a single symbol or an array. Multiple values create an OR filter. For a complete list of tracked companies and their symbols, refer to the /companies endpoint.
   */
  companySymbol: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles related to companies with specific stock symbols. Accepts either a single symbol or an array. Multiple values create an AND-exclude filter. For a complete list of tracked companies and their symbols, refer to the /companies endpoint.
   */
  excludeCompanySymbol: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by company name mentions. Accepts either a single name or an array. Performs exact matching on company names. Multiple values create an OR filter. For a complete list of tracked companies and their names, refer to the /companies endpoint.
   */
  companyName: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by Wikidata IDs of mentioned people. Accepts either a single ID or an array. Multiple values create an OR filter. For a complete list of tracked individuals and their Wikidata IDs, refer to the /people endpoint.
   */
  personWikidataId: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles mentioning people with specific Wikidata IDs. Accepts either a single ID or an array. Multiple values create an AND-exclude filter. For a complete list of tracked individuals and their Wikidata IDs, refer to the /people endpoint.
   */
  excludePersonWikidataId: z.array(z.string()).optional().nullable(),
  /**
   * Filter articles by exact person name matches. Accepts either a single name or an array. Does not support Boolean operators or wildcards. Multiple values create an OR filter. For a complete list of tracked individuals and their names, refer to the /people endpoint.
   */
  personName: z.array(z.string()).optional().nullable(),
  /**
   * Exclude articles mentioning specific people by name. Accepts either a single name or an array. Multiple values create an AND-exclude filter. For a complete list of tracked individuals and their names, refer to the /people endpoint.
   */
  excludePersonName: z.array(z.string()).optional().nullable(),
  /**
   * Adds additional AND filter objects. These objects must be of the same type as the original filter object and will be combined with the existing filter using the AND logical operator.
   */
  AND: z
    .array(
      z.unknown(),
    ) /* Self-reference to ArticleSearchFilterSchema prevented */
    .optional()
    .nullable(),
  /**
   * Adds additional OR filter objects. These objects must be of the same type as the original filter object and will be combined with the existing filter using the OR logical operator.
   */
  OR: z
    .array(
      z.unknown(),
    ) /* Self-reference to ArticleSearchFilterSchema prevented */
    .optional()
    .nullable(),
  /**
   * A filter object for logical NOT operations
   */
  NOT: z
    .array(
      z.unknown(),
    ) /* Self-reference to ArticleSearchFilterSchema prevented */
    .optional()
    .nullable(),
});

export type ArticleSearchFilter = z.infer<typeof ArticleSearchFilterSchema>;

export const ArticleSearchParamsSchema = z.object({
  /**
   * Natural language query to search the news articles database
   */
  prompt: z.string(),
  filter: ArticleSearchFilterSchema.optional().nullable(),
  /**
   * 'pubDateFrom' filter, will search articles published after the specified date, the date could be passed as ISO or 'yyyy-mm-dd'. Date time in ISO format, ie. 2024-01-01T00:00:00 - Default: Only articles with a pubDate within the last 30 days of the request
   */
  pubDateFrom: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * 'pubDateTo' filter, will search articles published before the specified date, the date could be passed as ISO or 'yyyy-mm-dd'. Date time in ISO format, ie. 2024-01-01T00:00:00
   */
  pubDateTo: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * Whether to return reprints in the response or not. Reprints are usually wired articles from sources like AP or Reuters that are reprinted in multiple sources at the same time. By default, this parameter is 'true'.
   */
  showReprints: z.boolean().optional().nullable(),
  /**
   * The number of items per page.
   */
  size: z.number().optional().nullable(),
  /**
   * The page number to retrieve.
   */
  page: z.number().optional().nullable(),
});

export type ArticleSearchParams = z.infer<typeof ArticleSearchParamsSchema>;

export const ScoredDataArticleSchema = z.object({
  score: z.number().optional().nullable(),
  data: ArticleSchema.optional().nullable(),
});

export type ScoredDataArticle = z.infer<typeof ScoredDataArticleSchema>;

export const ArticlesVectorSearchResultSchema = z.object({
  status: z.number(),
  results: z.array(ScoredDataArticleSchema),
});

export type ArticlesVectorSearchResult = z.infer<
  typeof ArticlesVectorSearchResultSchema
>;

export const ClustersListSortBySchema = z.enum([
  "createdAt",
  "updatedAt",
  "relevance",
  "count",
  "totalCount",
]);

export type ClustersListSortBy = z.infer<typeof ClustersListSortBySchema>;

export const ClustersListSortBy = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Relevance: "relevance",
  Count: "count",
  TotalCount: "totalCount",
} as const;

export const SymbolHolderSchema = z.object({
  symbol: z.string().optional().nullable(),
  exchange: z.string().optional().nullable(),
  exchangeShortName: z.string().optional().nullable(),
  ipoDate: z.string().optional().nullable(),
  isin: z.string().optional().nullable(),
  cusip: z.string().optional().nullable(),
});

export type SymbolHolder = z.infer<typeof SymbolHolderSchema>;

export const WebResourcesSchema = z.object({
  careers: z.string().optional().nullable(),
  about: z.string().optional().nullable(),
  blog: z.string().optional().nullable(),
  events: z.string().optional().nullable(),
  sitemap: z.string().optional().nullable(),
  updates: z.string().optional().nullable(),
  linkedin: z.string().optional().nullable(),
  facebook: z.string().optional().nullable(),
  instagram: z.string().optional().nullable(),
  medium: z.string().optional().nullable(),
  reddit: z.string().optional().nullable(),
  threads: z.string().optional().nullable(),
  tiktok: z.string().optional().nullable(),
  x: z.string().optional().nullable(),
  wellfound: z.string().optional().nullable(),
  youtube: z.string().optional().nullable(),
  wikipedia: z.string().optional().nullable(),
});

export type WebResources = z.infer<typeof WebResourcesSchema>;

export const CompanySchema = z.object({
  id: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  primaryRecordId: z.string().optional().nullable(),
  altNames: z.array(z.string()).optional().nullable(),
  domains: z.array(z.string()).optional().nullable(),
  monthlyVisits: z.number().optional().nullable(),
  globalRank: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  ceo: z.string().optional().nullable(),
  industry: z.string().optional().nullable(),
  sector: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  fullTimeEmployees: z.number().optional().nullable(),
  address: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  zip: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  favicon: z.string().optional().nullable(),
  isEtf: z.boolean().optional().nullable(),
  isActivelyTrading: z.boolean().optional().nullable(),
  isFund: z.boolean().optional().nullable(),
  isAdr: z.boolean().optional().nullable(),
  symbols: z.array(SymbolHolderSchema).optional().nullable(),
  naics: z.string().optional().nullable(),
  sic: z.string().optional().nullable(),
  cusip: z.string().optional().nullable(),
  cik: z.string().optional().nullable(),
  isin: z.string().optional().nullable(),
  yearFounded: z.number().optional().nullable(),
  revenue: z.string().optional().nullable(),
  webResources: WebResourcesSchema.optional().nullable(),
});

export type Company = z.infer<typeof CompanySchema>;

export const CompanySearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(CompanySchema),
});

export type CompanySearchResult = z.infer<typeof CompanySearchResultSchema>;

export const CreateSourceGroupParamsSchema = z.object({
  name: z.string(),
  displayName: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  domains: z.array(z.string()),
});

export type CreateSourceGroupParams = z.infer<
  typeof CreateSourceGroupParamsSchema
>;

export const ImageHolderSchema = z.object({
  url: z.string().optional().nullable(),
});

export type ImageHolder = z.infer<typeof ImageHolderSchema>;

export const WikidataDateHolderSchema = z.object({
  time: z.string().optional().nullable(),
  precision: z.string().optional().nullable(),
});

export type WikidataDateHolder = z.infer<typeof WikidataDateHolderSchema>;

export const WikidataLabelHolderSchema = z.object({
  wikidataId: z.string().optional().nullable(),
  label: z.string().optional().nullable(),
});

export type WikidataLabelHolder = z.infer<typeof WikidataLabelHolderSchema>;

export const WikidataPoliticalPartyHolderSchema = z.object({
  wikidataId: z.string().optional().nullable(),
  label: z.string().optional().nullable(),
  startTime: WikidataDateHolderSchema.optional().nullable(),
  endTime: WikidataDateHolderSchema.optional().nullable(),
});

export type WikidataPoliticalPartyHolder = z.infer<
  typeof WikidataPoliticalPartyHolderSchema
>;

export const WikidataPositionHolderSchema = z.object({
  wikidataId: z.string().optional().nullable(),
  label: z.string().optional().nullable(),
  startTime: WikidataDateHolderSchema.optional().nullable(),
  endTime: WikidataDateHolderSchema.optional().nullable(),
  employer: WikidataLabelHolderSchema.optional().nullable(),
});

export type WikidataPositionHolder = z.infer<
  typeof WikidataPositionHolderSchema
>;

export const PersonSchema = z.object({
  wikidataId: z.string().optional().nullable(),
  createdAt: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  gender: WikidataLabelHolderSchema.optional().nullable(),
  dateOfBirth: WikidataDateHolderSchema.optional().nullable(),
  dateOfDeath: WikidataDateHolderSchema.optional().nullable(),
  description: z.string().optional().nullable(),
  aliases: z.array(z.string()).optional().nullable(),
  occupation: z.array(WikidataLabelHolderSchema).optional().nullable(),
  position: z.array(WikidataPositionHolderSchema).optional().nullable(),
  politicalParty: z
    .array(WikidataPoliticalPartyHolderSchema)
    .optional()
    .nullable(),
  image: ImageHolderSchema.optional().nullable(),
  _abstract: z.string().optional().nullable(),
});

export type Person = z.infer<typeof PersonSchema>;

export const WatchlistCompanySchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  domain: z.string().optional().nullable(),
  aliases: z.array(z.string()).optional().nullable(),
  query: z.string().optional().nullable(),
});

export type WatchlistCompany = z.infer<typeof WatchlistCompanySchema>;

export const WatchlistPersonSchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  aliases: z.array(z.string()).optional().nullable(),
  wikidataId: z.string().optional().nullable(),
  query: z.string().optional().nullable(),
});

export type WatchlistPerson = z.infer<typeof WatchlistPersonSchema>;

export const CreateWatchlistParamsSchema = z.object({
  /**
   * Unique name for the watchlist within the organization
   */
  name: z.string(),
  /**
   * Display name for the watchlist
   */
  displayName: z.string().optional().nullable(),
  /**
   * Description of the watchlist
   */
  description: z.string().optional().nullable(),
  /**
   * List of people to include in the watchlist
   */
  people: z.array(WatchlistPersonSchema),
  /**
   * List of companies to include in the watchlist
   */
  companies: z.array(WatchlistCompanySchema),
  /**
   * Whether the watchlist is visible in the UI
   */
  visible: z.boolean().optional().nullable(),
});

export type CreateWatchlistParams = z.infer<typeof CreateWatchlistParamsSchema>;

export const ErrorResponseSchema = z.object({
  status: z.number().optional().nullable(),
  message: z.string().optional().nullable(),
  timestamp: z.number().optional().nullable(),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;

export const JournalistSearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(JournalistSchema),
});

export type JournalistSearchResult = z.infer<
  typeof JournalistSearchResultSchema
>;

export const JournalistsSortBySchema = z.enum([
  "avgMonthlyPosts",
  "linkedinConnections",
  "linkedinFollowers",
]);

export type JournalistsSortBy = z.infer<typeof JournalistsSortBySchema>;

export const JournalistsSortBy = {
  AvgMonthlyPosts: "avgMonthlyPosts",
  LinkedinConnections: "linkedinConnections",
  LinkedinFollowers: "linkedinFollowers",
} as const;

export const PatchSourceGroupParamsSchema = z.object({
  /**
   * Unique name for the source group within the organization
   */
  name: z.string().optional().nullable(),
  /**
   * Display name for the source group
   */
  displayName: z.string().optional().nullable(),
  /**
   * Description of the source group
   */
  description: z.string().optional().nullable(),
  /**
   * List of domains included in the source group
   */
  domains: z.array(z.string()).optional().nullable(),
});

export type PatchSourceGroupParams = z.infer<
  typeof PatchSourceGroupParamsSchema
>;

export const PeopleSearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(PersonSchema),
});

export type PeopleSearchResult = z.infer<typeof PeopleSearchResultSchema>;

export const QuerySearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  articles: z.array(ArticleSchema),
});

export type QuerySearchResult = z.infer<typeof QuerySearchResultSchema>;

export const WikiDataSchema = z.object({
  pageId: z.string().optional().nullable(),
  sectionId: z.string().optional().nullable(),
  wikiPageId: z.number().optional().nullable(),
  wikiRevisionId: z.number().optional().nullable(),
  wikiRevisionTs: z.string().optional().nullable(),
  wikiCode: z.string().optional().nullable(),
  wikiNamespace: z.number().optional().nullable(),
  wikiTitle: z.string().optional().nullable(),
  wikidataId: z.string().optional().nullable(),
  wikidataInstanceOf: z.array(WikidataLabelHolderSchema).optional().nullable(),
  redirectTitles: z.array(z.string()).optional().nullable(),
  pageviews: z.number().optional().nullable(),
  title: z.string().optional().nullable(),
  styleLevel: z.number().optional().nullable(),
  content: z.string().optional().nullable(),
});

export type WikiData = z.infer<typeof WikiDataSchema>;

export const ScoredDataWikiDataSchema = z.object({
  score: z.number().optional().nullable(),
  data: WikiDataSchema.optional().nullable(),
});

export type ScoredDataWikiData = z.infer<typeof ScoredDataWikiDataSchema>;

export const SourceTopStatHolderSchema = z.object({
  name: z.string().optional().nullable(),
  count: z.number().optional().nullable(),
});

export type SourceTopStatHolder = z.infer<typeof SourceTopStatHolderSchema>;

export const SourceSchema = z.object({
  id: z.string().optional().nullable(),
  domain: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  primaryRecordId: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  altNames: z.array(z.string()).optional().nullable(),
  description: z.string().optional().nullable(),
  avgMonthlyPosts: z.number().optional().nullable(),
  paywall: z.boolean().optional().nullable(),
  location: SourceLocationSchema.optional().nullable(),
  topCategories: z.array(SourceTopStatHolderSchema).optional().nullable(),
  topTopics: z.array(SourceTopStatHolderSchema).optional().nullable(),
  topCountries: z.array(SourceTopStatHolderSchema).optional().nullable(),
  topLabels: z.array(SourceTopStatHolderSchema).optional().nullable(),
  avgBiasRating: z.string().optional().nullable(),
  adFontesBiasRating: z.string().optional().nullable(),
  allSidesBiasRating: z.string().optional().nullable(),
  mbfcBiasRating: z.string().optional().nullable(),
  monthlyVisits: z.number().optional().nullable(),
  globalRank: z.number().optional().nullable(),
  logoLarge: ImageHolderSchema.optional().nullable(),
  logoFavIcon: ImageHolderSchema.optional().nullable(),
  logoSquare: ImageHolderSchema.optional().nullable(),
});

export type Source = z.infer<typeof SourceSchema>;

export const SourceGroupDtoSchema = z.object({
  /**
   * Numeric identifier for the source group.
   */
  id: z.number().optional().nullable(),
  /**
   * Date and time the source group was created, in ISO 8601 format.
   */
  createdAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * Date and time the source group was last updated, in ISO 8601 format.
   */
  updatedAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * Unique slug name for the source group.
   */
  name: z.string().optional().nullable(),
  /**
   * Human-readable display name.
   */
  displayName: z.string().optional().nullable(),
  /**
   * Optional description of the source group.
   */
  description: z.string().optional().nullable(),
  /**
   * Publisher domains included in the group.
   */
  domains: z.array(z.string()).optional().nullable(),
  /**
   * Owning organization ID when the source group is private.
   */
  organizationId: z.number().optional().nullable(),
  /**
   * Whether the source group is publicly visible.
   */
  visible: z.boolean().optional().nullable(),
});

export type SourceGroupDto = z.infer<typeof SourceGroupDtoSchema>;

export const SourceGroupListResultSchema = z.object({
  /**
   * Total number of matching source groups across all pages.
   */
  total: z.number(),
  /**
   * Source groups returned for the requested page.
   */
  data: z.array(SourceGroupDtoSchema),
});

export type SourceGroupListResult = z.infer<typeof SourceGroupListResultSchema>;

export const SourceGroupResolveResultSchema = z.object({
  /**
   * Resolved source groups.
   */
  data: z.array(SourceGroupDtoSchema),
});

export type SourceGroupResolveResult = z.infer<
  typeof SourceGroupResolveResultSchema
>;

export const SourceGroupResultSchema = z.object({
  data: SourceGroupDtoSchema,
});

export type SourceGroupResult = z.infer<typeof SourceGroupResultSchema>;

export const SourceGroupSortBySchema = z.enum([
  "id",
  "createdAt",
  "updatedAt",
  "name",
]);

export type SourceGroupSortBy = z.infer<typeof SourceGroupSortBySchema>;

export const SourceGroupSortBy = {
  Id: "id",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Name: "name",
} as const;

export const SourceSearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(SourceSchema),
});

export type SourceSearchResult = z.infer<typeof SourceSearchResultSchema>;

export const SourcesSortBySchema = z.enum([
  "globalRank",
  "relevance",
  "monthlyVisits",
  "avgMonthlyPosts",
]);

export type SourcesSortBy = z.infer<typeof SourcesSortBySchema>;

export const SourcesSortBy = {
  GlobalRank: "globalRank",
  Relevance: "relevance",
  MonthlyVisits: "monthlyVisits",
  AvgMonthlyPosts: "avgMonthlyPosts",
} as const;

export const StatResultSchema = z.object({
  /**
   * HTTP status code for the response.
   */
  status: z.number().optional().nullable(),
  /**
   * Statistics returned by the request.
   */
  results: z.array(z.unknown()).optional().nullable(),
  /**
   * Total number of matching records, when calculated by the endpoint.
   */
  numResults: z.number().optional().nullable(),
});

export type StatResult = z.infer<typeof StatResultSchema>;

export const StoryHistoryRecordSchema = z.object({
  /**
   * Unique identifier of the story associated with this history record.
   */
  clusterId: z.string().optional().nullable(),
  /**
   * Date and time the history record was created, in ISO 8601 format.
   */
  createdAt: z.string().optional().nullable(),
  /**
   * Story name captured in this history record, when available.
   */
  name: z.string().optional().nullable(),
  /**
   * Date and time the story refresh that produced this record was triggered, in ISO 8601 format.
   */
  triggeredAt: z.string().optional().nullable(),
  /**
   * Story summary captured in this history record.
   */
  summary: z.string().optional().nullable(),
  /**
   * Short story summary captured in this history record, when available.
   */
  shortSummary: z.string().optional().nullable(),
  /**
   * Description of changes from the previous story version, when available.
   */
  changelog: z.string().optional().nullable(),
  /**
   * Key points captured for this version of the story.
   */
  keyPoints: z.array(KeyPointSchema).optional().nullable(),
  /**
   * Questions and answers generated for this version of the story.
   */
  questions: z.array(QuestionSchema).optional().nullable(),
});

export type StoryHistoryRecord = z.infer<typeof StoryHistoryRecordSchema>;

export const StoryHistoryResultSchema = z.object({
  /**
   * HTTP status code for the response.
   */
  status: z.number(),
  /**
   * Total number of matching history records.
   */
  numResults: z.number(),
  /**
   * History records returned for the requested page.
   */
  results: z.array(StoryHistoryRecordSchema),
});

export type StoryHistoryResult = z.infer<typeof StoryHistoryResultSchema>;

export const StorySearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(NewsClusterSchema),
});

export type StorySearchResult = z.infer<typeof StorySearchResultSchema>;

export const SummaryBodySchema = z.object({
  /**
   * Instructions guiding how the summary should be written. Maximum length: 2,048 characters.
   */
  prompt: z.string().optional().nullable(),
  /**
   * Maximum number of articles used to generate the summary. Must be between 1 and 100.
   */
  maxArticleCount: z.number().optional().nullable(),
  /**
   * Maximum number of articles returned in the response. Must be between 1 and 100 and cannot return more articles than maxArticleCount selected.
   */
  returnedArticleCount: z.number().optional().nullable(),
  /**
   * Which article fields to include when generating the summary. Up to three values from TITLE, CONTENT, SUMMARY.
   */
  summarizeFields: z
    .enum(["TITLE", "CONTENT", "SUMMARY"])
    .optional()
    .nullable(),
  /**
   * Article selection method. ARTICLES selects up to maxArticleCount matching articles; CLUSTERS selects the first article from each of up to maxArticleCount stories.
   */
  method: z.enum(["ARTICLES", "CLUSTERS"]).optional().nullable(),
  /**
   * The underlying LLM model to use for generation.
   */
  model: z
    .enum([
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5-mini",
      "gpt-5-nano",
      "gpt-4o",
      "gpt-4o-mini",
      "gpt-4.1",
      "gpt-4.1-mini",
      "openai/gpt-oss-120b",
    ])
    .optional()
    .nullable(),
  /**
   * Sampling temperature from 0.0 to 2.0. Ignored by gpt-5.4-mini, gpt-5.4-nano, gpt-5-mini, and gpt-5-nano.
   */
  temperature: z.number().optional().nullable(),
  /**
   * Nucleus sampling (top-p) for the LLM (0.0 to 1.0).
   */
  topP: z.number().optional().nullable(),
  /**
   * Maximum number of tokens to generate. Must be 0 or greater.
   */
  maxTokens: z.number().optional().nullable(),
});

export type SummaryBody = z.infer<typeof SummaryBodySchema>;

export const SummarySearchResultSchema = z.object({
  /**
   * HTTP status code for the response.
   */
  status: z.number(),
  /**
   * Number of articles returned in results after applying returnedArticleCount.
   */
  numResults: z.number(),
  /**
   * Generated summary of the selected articles, or 'No articles found' when no content matches.
   */
  summary: z.string(),
  /**
   * Articles returned after summary generation, limited by returnedArticleCount.
   */
  results: z.array(ArticleSchema),
});

export type SummarySearchResult = z.infer<typeof SummarySearchResultSchema>;

export const TopicLabelsSchema = z.object({
  category: z.string().optional().nullable(),
  subcategory: z.string().optional().nullable(),
});

export type TopicLabels = z.infer<typeof TopicLabelsSchema>;

export const TopicDtoSchema = z.object({
  id: z.number().optional().nullable(),
  createdAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  updatedAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  name: z.string().optional().nullable(),
  labels: TopicLabelsSchema.optional().nullable(),
});

export type TopicDto = z.infer<typeof TopicDtoSchema>;

export const TopicSearchResultSchema = z.object({
  total: z.number(),
  data: z.array(TopicDtoSchema),
});

export type TopicSearchResult = z.infer<typeof TopicSearchResultSchema>;

export const UpdateWatchlistParamsSchema = z.object({
  /**
   * New name for the watchlist
   */
  name: z.string().optional().nullable(),
  /**
   * New display name for the watchlist
   */
  displayName: z.string().optional().nullable(),
  /**
   * New description for the watchlist
   */
  description: z.string().optional().nullable(),
  /**
   * Updated list of people to include in the watchlist
   */
  people: z.array(WatchlistPersonSchema).optional().nullable(),
  /**
   * Updated list of companies to include in the watchlist
   */
  companies: z.array(WatchlistCompanySchema).optional().nullable(),
  /**
   * Whether the watchlist is visible in the UI
   */
  visible: z.boolean().optional().nullable(),
});

export type UpdateWatchlistParams = z.infer<typeof UpdateWatchlistParamsSchema>;

export const WatchlistCompanyDtoSchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  domain: z.string().optional().nullable(),
  aliases: z.array(z.string()).optional().nullable(),
  query: z.string().optional().nullable(),
});

export type WatchlistCompanyDto = z.infer<typeof WatchlistCompanyDtoSchema>;

export const WatchlistPersonDtoSchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  wikidataId: z.string().optional().nullable(),
  aliases: z.array(z.string()).optional().nullable(),
  query: z.string().optional().nullable(),
});

export type WatchlistPersonDto = z.infer<typeof WatchlistPersonDtoSchema>;

export const WatchlistDtoSchema = z.object({
  /**
   * Numeric identifier for the watchlist.
   */
  id: z.number().optional().nullable(),
  /**
   * Date and time the watchlist was created, in ISO 8601 format.
   */
  createdAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * Date and time the watchlist was last updated, in ISO 8601 format.
   */
  updatedAt: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * Unique slug name for the watchlist.
   */
  name: z.string().optional().nullable(),
  /**
   * Human-readable display name.
   */
  displayName: z.string().optional().nullable(),
  /**
   * Optional description of the watchlist.
   */
  description: z.string().optional().nullable(),
  /**
   * People included in the watchlist.
   */
  people: z.array(WatchlistPersonDtoSchema).optional().nullable(),
  /**
   * Companies included in the watchlist.
   */
  companies: z.array(WatchlistCompanyDtoSchema).optional().nullable(),
  /**
   * Owning organization ID when the watchlist is private.
   */
  organizationId: z.number().optional().nullable(),
  /**
   * Whether the watchlist is publicly visible.
   */
  visible: z.boolean().optional().nullable(),
});

export type WatchlistDto = z.infer<typeof WatchlistDtoSchema>;

export const WatchlistListResultSchema = z.object({
  /**
   * Total number of matching watchlists across all pages.
   */
  total: z.number(),
  /**
   * Watchlists returned for the requested page.
   */
  data: z.array(WatchlistDtoSchema),
});

export type WatchlistListResult = z.infer<typeof WatchlistListResultSchema>;

export const WatchlistResolveResultSchema = z.object({
  /**
   * Resolved watchlists.
   */
  data: z.array(WatchlistDtoSchema),
});

export type WatchlistResolveResult = z.infer<
  typeof WatchlistResolveResultSchema
>;

export const WatchlistResultSchema = z.object({
  data: WatchlistDtoSchema,
});

export type WatchlistResult = z.infer<typeof WatchlistResultSchema>;

export const WatchlistSortBySchema = z.enum([
  "id",
  "createdAt",
  "updatedAt",
  "name",
]);

export type WatchlistSortBy = z.infer<typeof WatchlistSortBySchema>;

export const WatchlistSortBy = {
  Id: "id",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Name: "name",
} as const;

export const WikiPageSectionHolderSchema = z.object({
  id: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
  styleLevel: z.number().optional().nullable(),
  loc: z.array(z.number()).optional().nullable(),
  textRaw: z.string().optional().nullable(),
  textRich: z.string().optional().nullable(),
});

export type WikiPageSectionHolder = z.infer<typeof WikiPageSectionHolderSchema>;

export const WikiPageSchema = z.object({
  id: z.string().optional().nullable(),
  scrapedAt: z.string().optional().nullable(),
  wikiPageId: z.number().optional().nullable(),
  wikiRevisionId: z.number().optional().nullable(),
  wikiRevisionTs: z.string().optional().nullable(),
  wikiCode: z.string().optional().nullable(),
  wikiNamespace: z.number().optional().nullable(),
  wikiTitle: z.string().optional().nullable(),
  url: z.string().optional().nullable(),
  topImage: z.string().optional().nullable(),
  wikidataId: z.string().optional().nullable(),
  wikidataInstanceOf: z.array(WikidataLabelHolderSchema).optional().nullable(),
  redirectTitles: z.array(z.string()).optional().nullable(),
  summary: z.string().optional().nullable(),
  sections: z.array(WikiPageSectionHolderSchema).optional().nullable(),
  categories: z.array(z.string()).optional().nullable(),
  externalLinks: z.array(z.string()).optional().nullable(),
  references: z.array(z.string()).optional().nullable(),
  pageviews: z.number().optional().nullable(),
});

export type WikiPage = z.infer<typeof WikiPageSchema>;

export const WikipediaSearchFilterSchema = z.object({
  /**
   * Filter by specific Perigon page identifiers. Accepts either a single ID or an array of IDs. Returns only pages matching these IDs.
   */
  pageId: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific section identifiers. Accepts either a single ID or an array of IDs. Returns only pages containing these sections.
   */
  sectionId: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific Wikipedia page identifiers. Accepts either a single ID or an array of IDs. Returns only pages matching these IDs.
   */
  wikiPageId: z.array(z.number()).optional().nullable(),
  /**
   * Filter by specific Perigon page revision identifiers. Accepts either a single ID or an array of IDs. Returns only pages matching these IDs.
   */
  wikiRevisionId: z.array(z.number()).optional().nullable(),
  /**
   * Filter by specific Wikipedia project codes. Returns only pages matching these projects.
   */
  wikiCode: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific Wikipedia namespaces. Returns only pages matching these namespaces.
   */
  wikiNamespace: z.array(z.number()).optional().nullable(),
  /**
   * Filter by specific Wikidata entity IDs. Returns only pages whose Wikidata entities match those ids.
   */
  wikidataId: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific Wikidata entity IDs. Returns only pages whose Wikidata entities are instances of provided ids.
   */
  wikidataInstanceOfId: z.array(z.string()).optional().nullable(),
  /**
   * Filter by specific Wikidata entity labels. Returns only pages whose Wikidata entities are instances of these labels.
   */
  wikidataInstanceOfLabel: z.array(z.string()).optional().nullable(),
  /**
   * Adds additional AND filter objects. These objects must be of the same type as the original filter object and will be combined with the existing filter using the AND logical operator.
   */
  AND: z
    .array(
      z.unknown(),
    ) /* Self-reference to WikipediaSearchFilterSchema prevented */
    .optional()
    .nullable(),
  /**
   * Adds additional OR filter objects. These objects must be of the same type as the original filter object and will be combined with the existing filter using the OR logical operator.
   */
  OR: z
    .array(
      z.unknown(),
    ) /* Self-reference to WikipediaSearchFilterSchema prevented */
    .optional()
    .nullable(),
  /**
   * A filter object for logical NOT operations
   */
  NOT: z
    .array(
      z.unknown(),
    ) /* Self-reference to WikipediaSearchFilterSchema prevented */
    .optional()
    .nullable(),
});

export type WikipediaSearchFilter = z.infer<typeof WikipediaSearchFilterSchema>;

export const WikipediaSearchParamsSchema = z.object({
  /**
   * Natural language query to search the Wikipedia pages database
   */
  prompt: z.string(),
  filter: WikipediaSearchFilterSchema.optional().nullable(),
  /**
   * 'wikiRevisionFrom' filter, will search pages modified after the specified date, the date could be passed as ISO or 'yyyy-mm-dd'. Date time in ISO format, ie. 2024-01-01T00:00:00.
   */
  wikiRevisionFrom: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * 'wikiRevisionFrom' filter, will search pages modified before the specified date, the date could be passed as ISO or 'yyyy-mm-dd'. Date time in ISO format, ie. 2024-01-01T00:00:00.
   */
  wikiRevisionTo: z
    .union([z.iso.date(), z.iso.datetime()])
    .transform((val) => new Date(val))
    .optional()
    .nullable(),
  /**
   * 'pageviewsFrom' filter, will search pages with at least the provided number of views per day.
   */
  pageviewsFrom: z.number().optional().nullable(),
  /**
   * 'pageviewsFrom' filter, will search pages with at most the provided number of views per day.
   */
  pageviewsTo: z.number().optional().nullable(),
  /**
   * The number of items per page.
   */
  size: z.number().optional().nullable(),
  /**
   * The page number to retrieve.
   */
  page: z.number().optional().nullable(),
});

export type WikipediaSearchParams = z.infer<typeof WikipediaSearchParamsSchema>;

export const WikipediaSearchResultSchema = z.object({
  status: z.number(),
  numResults: z.number(),
  results: z.array(WikiPageSchema),
});

export type WikipediaSearchResult = z.infer<typeof WikipediaSearchResultSchema>;

export const WikipediaVectorSearchResultSchema = z.object({
  status: z.number(),
  results: z.array(ScoredDataWikiDataSchema),
});

export type WikipediaVectorSearchResult = z.infer<
  typeof WikipediaVectorSearchResultSchema
>;
