/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InternalErrorExceptionCauseStackTraceInner } from "./InternalErrorExceptionCauseStackTraceInner";
import {
  InternalErrorExceptionCauseStackTraceInnerFromJSON,
  InternalErrorExceptionCauseStackTraceInnerFromJSONTyped,
  InternalErrorExceptionCauseStackTraceInnerToJSON,
  InternalErrorExceptionCauseStackTraceInnerToJSONTyped,
} from "./InternalErrorExceptionCauseStackTraceInner";

/**
 *
 * @export
 * @interface InternalErrorExceptionSuppressedInner
 */
export interface InternalErrorExceptionSuppressedInner {
  /**
   *
   * @type {Array<InternalErrorExceptionCauseStackTraceInner>}
   * @memberof InternalErrorExceptionSuppressedInner
   */
  stackTrace?: Array<InternalErrorExceptionCauseStackTraceInner>;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionSuppressedInner
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionSuppressedInner
   */
  localizedMessage?: string;
}

/**
 * Check if a given object implements the InternalErrorExceptionSuppressedInner interface.
 */
export function instanceOfInternalErrorExceptionSuppressedInner(
  value: object,
): value is InternalErrorExceptionSuppressedInner {
  return true;
}

export function InternalErrorExceptionSuppressedInnerFromJSON(
  json: any,
): InternalErrorExceptionSuppressedInner {
  return InternalErrorExceptionSuppressedInnerFromJSONTyped(json, false);
}

export function InternalErrorExceptionSuppressedInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InternalErrorExceptionSuppressedInner {
  if (json == null) {
    return json;
  }
  return {
    stackTrace:
      json["stackTrace"] == null
        ? undefined
        : (json["stackTrace"] as Array<any>).map(
            InternalErrorExceptionCauseStackTraceInnerFromJSON,
          ),
    message: json["message"] == null ? undefined : json["message"],
    localizedMessage:
      json["localizedMessage"] == null ? undefined : json["localizedMessage"],
  };
}

export function InternalErrorExceptionSuppressedInnerToJSON(
  json: any,
): InternalErrorExceptionSuppressedInner {
  return InternalErrorExceptionSuppressedInnerToJSONTyped(json, false);
}

export function InternalErrorExceptionSuppressedInnerToJSONTyped(
  value?: InternalErrorExceptionSuppressedInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    stackTrace:
      value["stackTrace"] == null
        ? undefined
        : (value["stackTrace"] as Array<any>).map(
            InternalErrorExceptionCauseStackTraceInnerToJSON,
          ),
    message: value["message"],
    localizedMessage: value["localizedMessage"],
  };
}
