/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InternalErrorExceptionCauseStackTraceInner
 */
export interface InternalErrorExceptionCauseStackTraceInner {
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  classLoaderName?: string;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  moduleName?: string;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  moduleVersion?: string;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  methodName?: string;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  fileName?: string;
  /**
   *
   * @type {number}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  lineNumber?: number;
  /**
   *
   * @type {boolean}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  nativeMethod?: boolean;
  /**
   *
   * @type {string}
   * @memberof InternalErrorExceptionCauseStackTraceInner
   */
  className?: string;
}

/**
 * Check if a given object implements the InternalErrorExceptionCauseStackTraceInner interface.
 */
export function instanceOfInternalErrorExceptionCauseStackTraceInner(
  value: object,
): value is InternalErrorExceptionCauseStackTraceInner {
  return true;
}

export function InternalErrorExceptionCauseStackTraceInnerFromJSON(
  json: any,
): InternalErrorExceptionCauseStackTraceInner {
  return InternalErrorExceptionCauseStackTraceInnerFromJSONTyped(json, false);
}

export function InternalErrorExceptionCauseStackTraceInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InternalErrorExceptionCauseStackTraceInner {
  if (json == null) {
    return json;
  }
  return {
    classLoaderName:
      json["classLoaderName"] == null ? undefined : json["classLoaderName"],
    moduleName: json["moduleName"] == null ? undefined : json["moduleName"],
    moduleVersion:
      json["moduleVersion"] == null ? undefined : json["moduleVersion"],
    methodName: json["methodName"] == null ? undefined : json["methodName"],
    fileName: json["fileName"] == null ? undefined : json["fileName"],
    lineNumber: json["lineNumber"] == null ? undefined : json["lineNumber"],
    nativeMethod:
      json["nativeMethod"] == null ? undefined : json["nativeMethod"],
    className: json["className"] == null ? undefined : json["className"],
  };
}

export function InternalErrorExceptionCauseStackTraceInnerToJSON(
  json: any,
): InternalErrorExceptionCauseStackTraceInner {
  return InternalErrorExceptionCauseStackTraceInnerToJSONTyped(json, false);
}

export function InternalErrorExceptionCauseStackTraceInnerToJSONTyped(
  value?: InternalErrorExceptionCauseStackTraceInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    classLoaderName: value["classLoaderName"],
    moduleName: value["moduleName"],
    moduleVersion: value["moduleVersion"],
    methodName: value["methodName"],
    fileName: value["fileName"],
    lineNumber: value["lineNumber"],
    nativeMethod: value["nativeMethod"],
    className: value["className"],
  };
}
