/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Journalist } from "./Journalist";
import {
  JournalistFromJSON,
  JournalistFromJSONTyped,
  JournalistToJSON,
  JournalistToJSONTyped,
} from "./Journalist";

/**
 * Journalist search result
 * @export
 * @interface JournalistSearchResult
 */
export interface JournalistSearchResult {
  /**
   *
   * @type {number}
   * @memberof JournalistSearchResult
   */
  status?: number | null;
  /**
   *
   * @type {number}
   * @memberof JournalistSearchResult
   */
  numResults?: number | null;
  /**
   *
   * @type {Array<Journalist>}
   * @memberof JournalistSearchResult
   */
  results?: Array<Journalist> | null;
}

/**
 * Check if a given object implements the JournalistSearchResult interface.
 */
export function instanceOfJournalistSearchResult(
  value: object,
): value is JournalistSearchResult {
  return true;
}

export function JournalistSearchResultFromJSON(
  json: any,
): JournalistSearchResult {
  return JournalistSearchResultFromJSONTyped(json, false);
}

export function JournalistSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JournalistSearchResult {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : json["status"],
    numResults: json["numResults"] == null ? undefined : json["numResults"],
    results:
      json["results"] == null
        ? undefined
        : (json["results"] as Array<any>).map(JournalistFromJSON),
  };
}

export function JournalistSearchResultToJSON(
  json: any,
): JournalistSearchResult {
  return JournalistSearchResultToJSONTyped(json, false);
}

export function JournalistSearchResultToJSONTyped(
  value?: JournalistSearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    numResults: value["numResults"],
    results:
      value["results"] == null
        ? undefined
        : (value["results"] as Array<any>).map(JournalistToJSON),
  };
}
