/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface KeywordHolder
 */
export interface KeywordHolder {
  /**
   *
   * @type {string}
   * @memberof KeywordHolder
   */
  name?: string | null;
  /**
   *
   * @type {number}
   * @memberof KeywordHolder
   */
  weight?: number | null;
}

/**
 * Check if a given object implements the KeywordHolder interface.
 */
export function instanceOfKeywordHolder(value: object): value is KeywordHolder {
  return true;
}

export function KeywordHolderFromJSON(json: any): KeywordHolder {
  return KeywordHolderFromJSONTyped(json, false);
}

export function KeywordHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KeywordHolder {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    weight: json["weight"] == null ? undefined : json["weight"],
  };
}

export function KeywordHolderToJSON(json: any): KeywordHolder {
  return KeywordHolderToJSONTyped(json, false);
}

export function KeywordHolderToJSONTyped(
  value?: KeywordHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    weight: value["weight"],
  };
}
