/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NameCount
 */
export interface NameCount {
  /**
   *
   * @type {string}
   * @memberof NameCount
   */
  name?: string | null;
  /**
   *
   * @type {number}
   * @memberof NameCount
   */
  count?: number | null;
}

/**
 * Check if a given object implements the NameCount interface.
 */
export function instanceOfNameCount(value: object): value is NameCount {
  return true;
}

export function NameCountFromJSON(json: any): NameCount {
  return NameCountFromJSONTyped(json, false);
}

export function NameCountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NameCount {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    count: json["count"] == null ? undefined : json["count"],
  };
}

export function NameCountToJSON(json: any): NameCount {
  return NameCountToJSONTyped(json, false);
}

export function NameCountToJSONTyped(
  value?: NameCount | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    count: value["count"],
  };
}
