/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RecordStatHolder
 */
export interface RecordStatHolder {
  /**
   *
   * @type {string}
   * @memberof RecordStatHolder
   */
  name?: string | null;
  /**
   *
   * @type {number}
   * @memberof RecordStatHolder
   */
  count?: number | null;
}

/**
 * Check if a given object implements the RecordStatHolder interface.
 */
export function instanceOfRecordStatHolder(
  value: object,
): value is RecordStatHolder {
  return true;
}

export function RecordStatHolderFromJSON(json: any): RecordStatHolder {
  return RecordStatHolderFromJSONTyped(json, false);
}

export function RecordStatHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecordStatHolder {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    count: json["count"] == null ? undefined : json["count"],
  };
}

export function RecordStatHolderToJSON(json: any): RecordStatHolder {
  return RecordStatHolderToJSONTyped(json, false);
}

export function RecordStatHolderToJSONTyped(
  value?: RecordStatHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    count: value["count"],
  };
}
