/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Article } from "./Article";
import {
  ArticleFromJSON,
  ArticleFromJSONTyped,
  ArticleToJSON,
  ArticleToJSONTyped,
} from "./Article";

/**
 *
 * @export
 * @interface ScoredArticle
 */
export interface ScoredArticle {
  /**
   *
   * @type {number}
   * @memberof ScoredArticle
   */
  score?: number | null;
  /**
   *
   * @type {Article}
   * @memberof ScoredArticle
   */
  data?: Article;
}

/**
 * Check if a given object implements the ScoredArticle interface.
 */
export function instanceOfScoredArticle(value: object): value is ScoredArticle {
  return true;
}

export function ScoredArticleFromJSON(json: any): ScoredArticle {
  return ScoredArticleFromJSONTyped(json, false);
}

export function ScoredArticleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ScoredArticle {
  if (json == null) {
    return json;
  }
  return {
    score: json["score"] == null ? undefined : json["score"],
    data: json["data"] == null ? undefined : ArticleFromJSON(json["data"]),
  };
}

export function ScoredArticleToJSON(json: any): ScoredArticle {
  return ScoredArticleToJSONTyped(json, false);
}

export function ScoredArticleToJSONTyped(
  value?: ScoredArticle | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    score: value["score"],
    data: ArticleToJSON(value["data"]),
  };
}
