/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
  /**
   *
   * @type {number}
   * @memberof SearchResult
   */
  status?: number | null;
  /**
   *
   * @type {Array<object>}
   * @memberof SearchResult
   */
  results?: Array<object> | null;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
  return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
  return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchResult {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : json["status"],
    results: json["results"] == null ? undefined : json["results"],
  };
}

export function SearchResultToJSON(json: any): SearchResult {
  return SearchResultToJSONTyped(json, false);
}

export function SearchResultToJSONTyped(
  value?: SearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    results: value["results"],
  };
}
