/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StandardSearchResult
 */
export interface StandardSearchResult {
  /**
   *
   * @type {number}
   * @memberof StandardSearchResult
   */
  status?: number | null;
  /**
   *
   * @type {number}
   * @memberof StandardSearchResult
   */
  numResults?: number | null;
  /**
   *
   * @type {Array<object>}
   * @memberof StandardSearchResult
   */
  results?: Array<object> | null;
}

/**
 * Check if a given object implements the StandardSearchResult interface.
 */
export function instanceOfStandardSearchResult(
  value: object,
): value is StandardSearchResult {
  return true;
}

export function StandardSearchResultFromJSON(json: any): StandardSearchResult {
  return StandardSearchResultFromJSONTyped(json, false);
}

export function StandardSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StandardSearchResult {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : json["status"],
    numResults: json["numResults"] == null ? undefined : json["numResults"],
    results: json["results"] == null ? undefined : json["results"],
  };
}

export function StandardSearchResultToJSON(json: any): StandardSearchResult {
  return StandardSearchResultToJSONTyped(json, false);
}

export function StandardSearchResultToJSONTyped(
  value?: StandardSearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    numResults: value["numResults"],
    results: value["results"],
  };
}
