/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Article } from "./Article";
import {
  ArticleFromJSON,
  ArticleFromJSONTyped,
  ArticleToJSON,
  ArticleToJSONTyped,
} from "./Article";

/**
 *
 * @export
 * @interface SummarySearchResult
 */
export interface SummarySearchResult {
  /**
   *
   * @type {number}
   * @memberof SummarySearchResult
   */
  status?: number | null;
  /**
   *
   * @type {number}
   * @memberof SummarySearchResult
   */
  numResults?: number | null;
  /**
   *
   * @type {string}
   * @memberof SummarySearchResult
   */
  summary?: string | null;
  /**
   *
   * @type {Array<Article>}
   * @memberof SummarySearchResult
   */
  results?: Array<Article> | null;
}

/**
 * Check if a given object implements the SummarySearchResult interface.
 */
export function instanceOfSummarySearchResult(
  value: object,
): value is SummarySearchResult {
  return true;
}

export function SummarySearchResultFromJSON(json: any): SummarySearchResult {
  return SummarySearchResultFromJSONTyped(json, false);
}

export function SummarySearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SummarySearchResult {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : json["status"],
    numResults: json["numResults"] == null ? undefined : json["numResults"],
    summary: json["summary"] == null ? undefined : json["summary"],
    results:
      json["results"] == null
        ? undefined
        : (json["results"] as Array<any>).map(ArticleFromJSON),
  };
}

export function SummarySearchResultToJSON(json: any): SummarySearchResult {
  return SummarySearchResultToJSONTyped(json, false);
}

export function SummarySearchResultToJSONTyped(
  value?: SummarySearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    numResults: value["numResults"],
    summary: value["summary"],
    results:
      value["results"] == null
        ? undefined
        : (value["results"] as Array<any>).map(ArticleToJSON),
  };
}
