/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * A paginated search result containing a total count and list of data items. Note: This class is deprecated in favor of SliceResult for more efficient pagination
 * @export
 * @interface TableSearchResult
 */
export interface TableSearchResult {
  /**
   *
   * @type {number}
   * @memberof TableSearchResult
   */
  total?: number | null;
  /**
   *
   * @type {Array<object>}
   * @memberof TableSearchResult
   */
  data?: Array<object> | null;
}

/**
 * Check if a given object implements the TableSearchResult interface.
 */
export function instanceOfTableSearchResult(
  value: object,
): value is TableSearchResult {
  return true;
}

export function TableSearchResultFromJSON(json: any): TableSearchResult {
  return TableSearchResultFromJSONTyped(json, false);
}

export function TableSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableSearchResult {
  if (json == null) {
    return json;
  }
  return {
    total: json["total"] == null ? undefined : json["total"],
    data: json["data"] == null ? undefined : json["data"],
  };
}

export function TableSearchResultToJSON(json: any): TableSearchResult {
  return TableSearchResultToJSONTyped(json, false);
}

export function TableSearchResultToJSONTyped(
  value?: TableSearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    total: value["total"],
    data: value["data"],
  };
}
