/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TooManyRequestsExceptionCauseStackTraceInner } from "./TooManyRequestsExceptionCauseStackTraceInner";
import {
  TooManyRequestsExceptionCauseStackTraceInnerFromJSON,
  TooManyRequestsExceptionCauseStackTraceInnerFromJSONTyped,
  TooManyRequestsExceptionCauseStackTraceInnerToJSON,
  TooManyRequestsExceptionCauseStackTraceInnerToJSONTyped,
} from "./TooManyRequestsExceptionCauseStackTraceInner";

/**
 *
 * @export
 * @interface TooManyRequestsExceptionCause
 */
export interface TooManyRequestsExceptionCause {
  /**
   *
   * @type {Array<TooManyRequestsExceptionCauseStackTraceInner>}
   * @memberof TooManyRequestsExceptionCause
   */
  stackTrace?: Array<TooManyRequestsExceptionCauseStackTraceInner>;
  /**
   *
   * @type {string}
   * @memberof TooManyRequestsExceptionCause
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof TooManyRequestsExceptionCause
   */
  localizedMessage?: string;
}

/**
 * Check if a given object implements the TooManyRequestsExceptionCause interface.
 */
export function instanceOfTooManyRequestsExceptionCause(
  value: object,
): value is TooManyRequestsExceptionCause {
  return true;
}

export function TooManyRequestsExceptionCauseFromJSON(
  json: any,
): TooManyRequestsExceptionCause {
  return TooManyRequestsExceptionCauseFromJSONTyped(json, false);
}

export function TooManyRequestsExceptionCauseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TooManyRequestsExceptionCause {
  if (json == null) {
    return json;
  }
  return {
    stackTrace:
      json["stackTrace"] == null
        ? undefined
        : (json["stackTrace"] as Array<any>).map(
            TooManyRequestsExceptionCauseStackTraceInnerFromJSON,
          ),
    message: json["message"] == null ? undefined : json["message"],
    localizedMessage:
      json["localizedMessage"] == null ? undefined : json["localizedMessage"],
  };
}

export function TooManyRequestsExceptionCauseToJSON(
  json: any,
): TooManyRequestsExceptionCause {
  return TooManyRequestsExceptionCauseToJSONTyped(json, false);
}

export function TooManyRequestsExceptionCauseToJSONTyped(
  value?: TooManyRequestsExceptionCause | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    stackTrace:
      value["stackTrace"] == null
        ? undefined
        : (value["stackTrace"] as Array<any>).map(
            TooManyRequestsExceptionCauseStackTraceInnerToJSON,
          ),
    message: value["message"],
    localizedMessage: value["localizedMessage"],
  };
}
