/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TopicDto } from "./TopicDto";
import {
  TopicDtoFromJSON,
  TopicDtoFromJSONTyped,
  TopicDtoToJSON,
  TopicDtoToJSONTyped,
} from "./TopicDto";

/**
 * Topic search result
 * @export
 * @interface TopicSearchResult
 */
export interface TopicSearchResult {
  /**
   *
   * @type {number}
   * @memberof TopicSearchResult
   */
  total: number;
  /**
   *
   * @type {Array<TopicDto>}
   * @memberof TopicSearchResult
   */
  data: Array<TopicDto>;
}

/**
 * Check if a given object implements the TopicSearchResult interface.
 */
export function instanceOfTopicSearchResult(
  value: object,
): value is TopicSearchResult {
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function TopicSearchResultFromJSON(json: any): TopicSearchResult {
  return TopicSearchResultFromJSONTyped(json, false);
}

export function TopicSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopicSearchResult {
  if (json == null) {
    return json;
  }
  return {
    total: json["total"],
    data: (json["data"] as Array<any>).map(TopicDtoFromJSON),
  };
}

export function TopicSearchResultToJSON(json: any): TopicSearchResult {
  return TopicSearchResultToJSONTyped(json, false);
}

export function TopicSearchResultToJSONTyped(
  value?: TopicSearchResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    total: value["total"],
    data: (value["data"] as Array<any>).map(TopicDtoToJSON),
  };
}
