/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TopicLabels
 */
export interface TopicLabels {
  /**
   *
   * @type {string}
   * @memberof TopicLabels
   */
  category?: string | null;
  /**
   *
   * @type {string}
   * @memberof TopicLabels
   */
  subcategory?: string | null;
}

/**
 * Check if a given object implements the TopicLabels interface.
 */
export function instanceOfTopicLabels(value: object): value is TopicLabels {
  return true;
}

export function TopicLabelsFromJSON(json: any): TopicLabels {
  return TopicLabelsFromJSONTyped(json, false);
}

export function TopicLabelsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopicLabels {
  if (json == null) {
    return json;
  }
  return {
    category: json["category"] == null ? undefined : json["category"],
    subcategory: json["subcategory"] == null ? undefined : json["subcategory"],
  };
}

export function TopicLabelsToJSON(json: any): TopicLabels {
  return TopicLabelsToJSONTyped(json, false);
}

export function TopicLabelsToJSONTyped(
  value?: TopicLabels | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category: value["category"],
    subcategory: value["subcategory"],
  };
}
