/* tslint:disable */
/* eslint-disable */
/**
 * Perigon API
 * The Perigon API provides access to comprehensive news and web content data. To use the API, simply sign up for a Perigon Business Solutions account to obtain your API key. Your available features may vary based on your plan. See the Authentication section for details on how to use your API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: data@perigon.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WikidataDateHolder
 */
export interface WikidataDateHolder {
  /**
   *
   * @type {string}
   * @memberof WikidataDateHolder
   */
  time?: string | null;
  /**
   *
   * @type {string}
   * @memberof WikidataDateHolder
   */
  precision?: string | null;
}

/**
 * Check if a given object implements the WikidataDateHolder interface.
 */
export function instanceOfWikidataDateHolder(
  value: object,
): value is WikidataDateHolder {
  return true;
}

export function WikidataDateHolderFromJSON(json: any): WikidataDateHolder {
  return WikidataDateHolderFromJSONTyped(json, false);
}

export function WikidataDateHolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WikidataDateHolder {
  if (json == null) {
    return json;
  }
  return {
    time: json["time"] == null ? undefined : json["time"],
    precision: json["precision"] == null ? undefined : json["precision"],
  };
}

export function WikidataDateHolderToJSON(json: any): WikidataDateHolder {
  return WikidataDateHolderToJSONTyped(json, false);
}

export function WikidataDateHolderToJSONTyped(
  value?: WikidataDateHolder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    time: value["time"],
    precision: value["precision"],
  };
}
