name: TypeScript SDK Tests

on:
  push:
    branches: [main]
    paths: ["src/**", "tests/**"]
  pull_request:
    branches: [main]
    paths: ["src/**", "tests/**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test
        env:
          PERIGON_API_KEY: ${{ secrets.PERIGON_API_KEY }}
