name: TypeScript SDK Tests

on:
  push:
    branches: [main]
    paths: ["src/**", "tests/**"]
  pull_request:
    branches: [main]
    paths: ["src/**", "tests/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          PERIGON_API_KEY: ${{ secrets.PERIGON_API_KEY }}
